name: .NET Core Publish

on:
  push:
    paths:
      - 'Agrogestor360/src/Agrogestor360.Server/Agrogestor360.Server/**'
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal    

    - name: Publish
      run: dotnet publish --configuration Release --runtime win-x64 --no-build --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Agrogestor360Server
        path: ./publish/
